### ISSUE TITLE
Doesn't Render with Svelte 5

### ISSUE THREAD

**Issue by skamansam** [rafalou38/svelte-preview#24]
**Describe the bug**
I am using this for the first time and I can't get it to render at all. I am using a new svelte 5 app and the preview isn't working at all. I am using the Windsurf editor as well. I am seeing errors in the errors tab in the preview, (eg "component has unused export property..."), but nothing is displaying in the preview area.

**To Reproduce**
1. Create a new svelte 5 repo with `pnpx sv create demo-project`
  a. make sure the library option is specified
1. Create a new component in `src/lib/`
1. Open the component and open the preview

**Expected behavior**
The preview should render the component.

**Logs**
[vscode-app-1735058137029.log](https://github.com/user-attachments/files/18240956/vscode-app-1735058137029.log)

**Screenshots**
![image](https://github.com/user-attachments/assets/741af3da-f83b-484f-bbea-c279c476dd4e)

**Version:**
2.7.1

**Additional context**

**Comment by skamansam** [comment]
This also happens in code-insiders 1.97.0-1734675033.el8

**Comment by rafalou38** [comment]
I'll try to have a look at that.
Just to be sure, does the issues persist if you remove export on the `items` and `title` or use the `items` in you components ?

**Comment by skamansam** [comment]
![image](https://github.com/user-attachments/assets/09addc68-a1f1-4ab9-b356-50eedd8b2fbc)
it happens with an empty script tag and without a script tag

**Comment by rafalou38** [comment]
The issue here seems not to come from svelte-preview but from your code.
I have never seen this kind of template syntax in svelte, are you confusing with vue SFC ?

From what I know, this is not standard in svelte, did you mean to use the `slot` feature  ?

Your code is not displaying event when used in the standard way through the svelte compiler and browser.


If you look here, the extension and browser only displays what's after the `template`.


![image](https://github.com/user-attachments/assets/b959ec92-04d9-49cd-ad40-0c3d7e4d851e)

Feel free to let me know if it's a feature svelte-preview should support.

**Comment by skamansam** [comment]
Oh, geez! I'm so sorry! I use svelte in my personal projects and vue at my job. IT certainly looks like I got them confused. I am so sorry for wasting your valuable time. I will be more diligent in the future. Thank you so much!
